### ISSUE TITLE
HTTP 413 during sync with very large network/pool list

### ISSUE THREAD

**Issue by halbig** [gomorpheus/morpheus-efficientip-plugin#1] opened 2022-05-03 19:49 UTC
We have a very large number of networks and pools in EfficientIP. After successfully compiling the list of networks and pools from EfficientIP, it seems that the POST method on the Morpheus server throws a 413 Payload Too Large error. This is resulting in networks and pools not being synchronized.

Log example:

2022-05-03_16:01:14.75207 ''[2022-05-03 16:01:17,757] [logFlush-8] [1;31mERROR[0;39m [36mc.m.g.e.ElasticService[0;39m - error executing bulk request: method [POST], host [http://127.0.0.1:9200], URI [/_bulk], status line [HTTP/1.1 413 Request Entity Too Large]
2022-05-03_16:01:17.75812  
2022-05-03_16:01:17.75813 'org.elasticsearch.client.ResponseException: method [POST], host [http://127.0.0.1:9200], URI [/_bulk], status line [HTTP/1.1 413 Request Entity Too Large]

**Comment by halbig** [comment] 2022-05-03 19:54
As a side note, I guess a fix would be to break up the POST into smaller payloads, but it would also be great (perhaps in a future version) if we could filter and select a smaller number of networks to import instead of bringing in everything.

**Comment by davydotcom** [comment] 2022-05-03 20:20
That error seems odd. So it's not efficient ip that's complaining it's elastic ? Elastic is for global search and a background task it should not be impacting your synced network list

**Comment by halbig** [comment] 2022-05-03 20:44
Well, I thought this was the culprit based on this error showing each time a sync was attempted. There are some other errors as well, but they are related to validation on specific networks and I didn't think they'd be causing many more networks to fail to sync. Attached a text file with some examples of the log entries.

[log_examples.txt](https://github.com/gomorpheus/morpheus-efficientip-plugin/files/8614192/log_examples.txt)

**Comment by halbig** [comment] 2022-05-03 21:00
Also, EfficientIP is not complaining. The plugin outputs the result of the responses from EfficientIP in the log, and it does show a full response with the literally thousands of networks we have. Only 450 got successfully synced into Morpheus.

**Comment by davydotcom** [comment] 2022-05-03 23:39
```
2022-05-03_16:01:12.44955 - Field error in object 'com.morpheus.NetworkPool' on field 'name': rejected value [null]; codes [com.morpheus.NetworkPool.name.nullable.error.com.morpheus.NetworkPool.name,com.morpheus.NetworkPool.name.nullable.error.name,com.morpheus.NetworkPool.name.nullable.error.java.lang.String,com.morpheus.NetworkPool.name.nullable.error,networkPool.name.nullable.error.com.morpheus.NetworkPool.name,networkPool.name.nullable.error.name,networkPool.name.nullable.error.java.lang.String,networkPool.name.nullable.error,com.morpheus.NetworkPool.name.nullable.com.morpheus.NetworkPool.name,com.morpheus.NetworkPool.name.nullable.name,com.morpheus.NetworkPool.name.nullable.java.lang.String,com.morpheus.NetworkPool.name.nullable,networkPool.name.nullable.com.morpheus.NetworkPool.name,networkPool.name.nullable.name,networkPool.name.nullable.java.lang.String,networkPool.name.nullable,nullable.com.morpheus.NetworkPool.name,nullable.name,nullable.java.lang.String,nullable]; arguments [name,class com.morpheus.NetworkPool]; default message [Please enter a {0}]
```
The name is null on one of the network subnets causing us to fail to sync the rest. It's either a blank pool name or subnet name, looking

**Comment by davydotcom** [comment] 2022-05-03 23:44
I have a fix for above to fallback to a default name of the range if no name on the subnet. As for the duplicate ips its basically saying you have a network subnet/pool with duplicate ip rows for the same ip. if you could dig into what those ips look like in efficient ip that might help me figure out what to do with those ones.

**Comment by davydotcom** [comment] 2022-05-03 23:45
Also yes right now if a single network create fails it stops progressing. This was temporary to catch any surprises .

**Comment by halbig** [comment] 2022-05-03 23:50
Aha, now I understand. Thanks for this info! I was going to dig into the "null" name and the duplicates later; I did not realize that they could have stopped the process. I will check on these when I get a chance this week.

**Comment by halbig** [comment] 2022-05-09 17:56
Hi David. I had three pairs of eyes looking at those IPs marked as "must be unique" and we don't see anything strange or even similar between them. One is in a DHCP pool marked as Reserved but Not In Use, one is in a DHCP pool marked as Reserved and Assigned, and one is not in a DHCP pool at all. We don't see anything in EfficientIP that would suggest they are somehow duplicated.

**Comment by halbig** [comment] 2022-05-20 00:29
Hi again, David. Where should we go from here? I'm happy to work with you on getting this fixed up, I just need to know how to proceed. If we can talk outside of this forum that would be great. Thanks!

**Comment by davydotcom** [comment] 2022-05-26 13:55
Thanks for the info! I think i may have a fix for the ip issue. Were you able to determine the cause of the no name networks? Happy to do a call

**Comment by halbig** [comment] 2022-06-02 13:35
Hi Dave. We have several networks that aren't named at present. If the plugin can assign a default name that would be great. You can shoot me an e-mail at clh291@psu.edu if you want to discuss further or if we need to schedule a call. Thanks!

**Comment by davydotcom** [comment] 2023-08-17 21:28
forgot to close this as this was resolved. sorry!

**Closed as completed by davydotcom** 2023-08-17 21:28 UTC
